### ISSUE TITLE
Why can't I reproduct the effect on the paper

### ISSUE THREAD

**Issue by akafen** [alterzero/DBPN-Pytorch#10]
Hello,I use your code to run,but ths psnr always is 35.x tested on Set5 which the scale factor is 2 ，but the paper is 38.09.I wonder why?

**Comment by ynieWXJB** [comment]
Can you run all the 5 images of Set5? I can only run three of them.

**Comment by alterzero** [comment]
Hi @akafen , How did you calculate the PSNR? In the paper, the measurement used luminance layer only.

@alexnie1997 We use TITAN X. If you have less memory, try to run the evaluation using --chop_forward True (This function is implemented by EDSR team https://github.com/thstkdgus35/EDSR-PyTorch)

**Comment by akafen** [comment]
Hi @alterzero,I calculated the PSNR on RGB images,but I think it should not have such a big difference and I would try to calculate the PSNR using luminance layer only.

**Comment by wehkjhkl** [comment]
Can you run eval.py?how can you do it?

**Comment by LoSealL** [comment]
@akafen The difference could be up to 2dB.
