### ISSUE TITLE
Training

### ISSUE THREAD

**Issue by JadenLy** [alterzero/DBPN-Pytorch#11]
Hello, 

Thanks for your impressive work here. 
I am interested in training a DBPN model with my own data. So could you please tell a few details on the setup? Such as where I put my training data (LR and HR), the format of data. 

Thank you

**Comment by alterzero** [comment]
You just need to modify dataset.py especially between line 74 and 89
and define --data_dir , --hr_train_dataset , --train_dataset in the main.py correlated with your own dataset.

**Comment by wehkjhkl** [comment]
If I have high resolution images in different size,hou can I generate the corresponding low resolution images?

**Comment by alterzero** [comment]
@wehkjhkl if you assume the downscaling operator is Bicubic, you can use MATLAB (imresize). Bicubic downsampling is the most common setting from the recent single-image super-resolution.

**Comment by ZhangDY827** [comment]
@alterzero Hello,  I want to reproduce your result recently, but meet some difficulties。I first generate the pairs of HR and LR through Bicubic downsampling using MATLAB, then directly train the network. However, the result is not satisfactory.  I want to know if you only use the 800 images from DIV2K dataset to train the DBPN, not expand the amount of training dataset by data augmentation.

**Comment by alterzero** [comment]
@CasdDesnDR your guess is right, we have offline data augmentation to expand the training set. The simplest thing you can do is to downscale the HR image into several size (such as: 0.9, 0.8, 0.5), then produce the corresponding LR image.

**Comment by xiaoloutongxue** [comment]
Hi, I try to training you network, but there always exist out of memory problem, even two 1080 Ti x were used. I wonder to ask how much GPUs used in your work?

**Comment by wehkjhkl** [comment]
have you solved the problem?I meet the same question. @xiaoloutongxue

**Comment by xiaoloutongxue** [comment]
@wehkjhkl Run this network may need four gpus, because the default gpu number is four in author's code.

**Comment by wehkjhkl** [comment]
I use four gpus,but it does not work. @xiaoloutongxue

**Comment by wehkjhkl** [comment]
Can you get the result when running eval.py? @xiaoloutongxue

**Comment by xiaoloutongxue** [comment]
@wehkjhkl I really don't know now, we need wait author to response this problem..... I have try SRCNN in this frame, but i can't get the same result which presented in author's paper even the data augmentation have been applied. So, i am confused.

**Comment by alterzero** [comment]
For x8, we use 8 GPUs (TITANX). But for x4, 4 GPUs should be enough.

**Comment by xiaoloutongxue** [comment]
@alterzero Should I train the model from x2 to x8 or training x8 directly? I train x4 directly, but i can't get your result.

**Comment by qingchuanhuajuan** [comment]
Run python3 eval.py, no SR picture. Only the following sentences, can you achieve it?


Namespace(chop_forward=True, gpu_mode=True, gpus=1, input_dir='Input', model='models/DBPN_x4.pth', model_type='DBPNL', output='Results/', seed=123, self_ensemble=True, testBatchSize=1, test_dataset='Set5_LR_x4', threads=1, upscale_factor=4)
===> Loading datasets
===> Building model
Pre-trained SR model is loaded.

**Comment by JeasonUESTC** [comment]
@xiaoloutongxue Hi, I meet the same problem with using two GPUs due to the laboratory conditions. Have you succeeded?

**Comment by zhuwanling** [comment]
@alterzero    
When running eval.py the dataset 0002x8.png will runtimeError: cuda runtime error (2) : out of memory , however 0003x8.png is OK, if 0002x8.png is too large;
My GPU is 12G ，pytorch0.3.1
