### ISSUE TITLE
there is an error...

### ISSUE THREAD

**Issue by wehkjhkl** [alterzero/DBPN-Pytorch#12]
===> Loading datasets
===> Building model
/home/amax/hao/DBPN-Pytorch-master/dbpn_v1.py:53: UserWarning: nn.init.kaiming_normal is now deprecated in favor of nn.init.kaiming_normal_.
  torch.nn.init.kaiming_normal(m.weight)
/home/amax/hao/DBPN-Pytorch-master/dbpn_v1.py:57: UserWarning: nn.init.kaiming_normal is now deprecated in favor of nn.init.kaiming_normal_.
  torch.nn.init.kaiming_normal(m.weight)
Pre-trained SR model is loaded.
Do you know this error when I run eval.py

**Comment by alterzero** [comment]
This code runs on PyTorch 0.3.1
Usually this warning happen when you use newer version
