### ISSUE TITLE
CUDA error: out of memory

### ISSUE THREAD

**Issue by jotoy** [alterzero/DBPN-Pytorch#14]
I got a runtime error: CUDA error: out of memory

**Comment by alterzero** [comment]
We used PyTorch 0.3.1 on NVIDIA TITANX 12G

**Comment by llj666666** [comment]
今年4月份我在gtx1060(6G)下可以运行，现在会出现： RuntimeError: CUDA error: out of memory

**Comment by qingchuanhuajuan** [comment]
@llj666666  
Are you getting an error when running "python3  main.py"? I am getting an error "local variable 'input' referenced before assignment". I modified "input" but it didn't work. How can you solve this problem?

**Comment by Frog-Michael** [comment]
> We used PyTorch 0.3.1 on NVIDIA TITANX 12G

Hi
I used main.py to train model successfully,
but when I use the trained models & eval.py to test, I got "CUDA error: out of memory"
then I tried the pretrained model you provided in https://drive.google.com/drive/folders/1ahbeoEHkjxoo4NV1wReOmpoRWbl448z-?usp=sharing, I also got "CUDA error: out of memory"

my env:
PyTorch: 0.4.1
Python: 3.5.6 & 2.7.5
GPU: Two Tesla P40(20G), all 40G

**Comment by NoushNabi** [comment]
I get the same message during evaluation. 
CUDA error: out of memory
Any advice?

**Comment by zhuwanling** [comment]
@Frog-Michael I have the same problem as you, have you solved it?

**Comment by jotoy** [comment]
Try to change the version of pytorch, which is same as  the author used.

发自我的 iPhone

**Comment by zhuwanling** [comment]
@jotoy 
thank you for your reply
                                Whether There’s a problem with Python’s multiprocessing where it doesn’t always clean up the child processes properly.  Can you give me some suggestions for the solution except the replacement version.
