### ISSUE TITLE
training dataset

### ISSUE THREAD

**Issue by suke27** [alterzero/DBPN-Pytorch#15]
Hello, could you share x8 training dataset? default DIV2k has no x8 images

**Comment by alterzero** [comment]
It is available here
HR: 
http://data.vision.ee.ethz.ch/cvl/DIV2K/DIV2K_train_HR.zip
Val x8: 
https://competitions.codalab.org/my/datasets/download/4ccbd8c6-8af2-4310-ae9a-5f25b2a6d65
2LR x8: https://competitions.codalab.org/my/datasets/download/70ccff08-fda4-4e09-ad9f-cb28b170ece9

**Comment by JeasonUESTC** [comment]
@alterzero Hi, the link address of  HR and  Val x8. Could you share them again?

**Comment by zhuwanling** [comment]
the link address of HR and Val x8.    Could you share them again?

**Comment by chroota** [comment]
the link address of HR and Val x8. Could you share them again?

**Comment by george-gca** [comment]
If you, like me, came here and tried to download the datasets, found that the valid part link is broken. The good news is that there is only one missing char, and I started trying one by one. Thankfully, it did not take me too long to find the right one. Here is the correct link: https://competitions.codalab.org/my/datasets/download/4ccbd8c6-8af2-4310-ae9a-5f25b2a6d652
