### ISSUE TITLE
set14——test

### ISSUE THREAD

**Issue by qingchuanhuajuan** [alterzero/DBPN-Pytorch#18]
There is a picture (bridge) in set 14 that is single-channel, but the trained model requires that the input picture be three-channel. How did you solve this problem in the experiment?

**Comment by Zheng222** [comment]
@qingchuanhuajuan you can simply duplicate the data to another two channels.

**Comment by qingchuanhuajuan** [comment]
Thank you! When I tested the X4 model, the image size in set14 was not a multiple of 4. I used the imresize() function in matlab to adjust the test image to an integer multiple of 4. How do you solve this problem?

**Comment by Zheng222** [comment]
@qingchuanhuajuan According to conventional practice, you should crop the right and bottom parts of image.
```
def modcrop(im, module):
      sz = im.shape
      h = np.int32(sz[0]/module) * module
      w = np.int32(sz[1]/module)* module
      ims = im[0:h, 0:w, ...]
      return ims
```
