### ISSUE TITLE
local variable 'input' referenced before assignment

### ISSUE THREAD

**Issue by jotoy** [alterzero/DBPN-Pytorch#20]
UnboundLocalError: local variable 'input' referenced before assignment

**Comment by qingchuanhuajuan** [comment]
Hello, I also encountered the same error when running the “main.py ”file. I modified it, but there are still errors. How can you solve this problem?

**Comment by qingchuanhuajuan** [comment]
@jotoy Modify the name of the dataset in dataset.py. This LR name should be the same as in main.py.

**Comment by jotoy** [comment]
> Hello, I also encountered the same error when running the “main.py ”file. I modified it, but there are still errors. How can you solve this problem?

you may find the class DatasetFromFolder in dataset.py.
then you should change the dataset name if self.dataset == 'DIV2K_train_LR_aug_x8': to the right name you are used.

**Comment by qingchuanhuajuan** [comment]
Yes, that's it. Guarantee the same name
