### ISSUE TITLE
DBPN_x8.pth load error

### ISSUE THREAD

**Issue by suke27** [alterzero/DBPN-Pytorch#21]
Hello, when I try to use DBPN_x8 model below error occurs
RuntimeError: invalid argument 2: sizes do not match at /pytorch/torch/lib/THC/generic/THCTensorCopy.c:48

DBPN_x8.pth is it not for x8, any difference with NTIRE2018_x8.pth?

**Comment by Liber-coder** [comment]
I encountered similar problem when I changed the **--mode**l from **NTIRE2018_x8** to **DBPN_x8** in the file **eval.py**. And I solved the problem after changing **--model_type** from **DBPNNL** to **DBPN** or other.

I hope this method is also useful for you. :)

**Comment by suke27** [comment]
yes, I also found it. thank you!
