### ISSUE TITLE
gpus should be int

### ISSUE THREAD

**Issue by drStacky** [alterzero/DBPN-Pytorch#25]
In the training script main.py, the number of gpus should be in not float:

https://github.com/alterzero/DBPN-Pytorch/blob/9b4b529fc80c7e1732188ce4ef279c4fe294aa86/main.py#L30

The problem is when it's used to make a range:

https://github.com/alterzero/DBPN-Pytorch/blob/9b4b529fc80c7e1732188ce4ef279c4fe294aa86/main.py#L45

**Comment by drStacky** [comment]
Same problem in eval.py

**Comment by alterzero** [comment]
Thank you!
