### ISSUE TITLE
Out of Memory for upscale factor 2 on images 256X256

### ISSUE THREAD

**Issue by NeuralBricolage** [alterzero/DBPN-Pytorch#26]
I'm running on GTX 1080TI  - i can upscale 2X images of 128X128 but results are quite bad  - even colors are all off; but on 256X256 i'm running out of memory

python  eval.py --upscale_factor=2 --model_type=DBPN   --test_dataset=dset --model=models/DBPN_x2.pth

what are the GPU RAM expectations? if i add another 1080 will it solve the problem?

thank you

**Comment by alterzero** [comment]
Set flag --chop_forward to True for small memory GPU

**Comment by NeuralBricolage** [comment]
--chop_forward=True is the default - and i didn't help - i'm still getting OOM - and tbh i won't consider 1080TI to be a small memory GPU
