### ISSUE TITLE
about the subtractor and the minuend

### ISSUE THREAD

**Issue by nick-zoo** [alterzero/DBPN-Pytorch#29]
Hello, I am a fresh learner about the super-resolution,I read the _Deep Back-Projection Networks For Super-Resolution_carefully,and I want to know why is the changed feature map minus the original feature map  in the residual process? thanks!

**Comment by alterzero** [comment]
This schema is inspired by back-projection.
You can read this paper for further details
http://www.weizmann.ac.il/math/irani/sites/math.irani/files/uploads/cvgip-sr-1991_.pdf
