### ISSUE TITLE
[Maybe BUG] Output image's brightness is wrong

### ISSUE THREAD

**Issue by LoSealL** [alterzero/DBPN-Pytorch#30]
I'm using the pre-trained model downloaded from [DBPNLL_x8](https://drive.google.com/drive/folders/1NTR-4hpX5gkWyZj0lArv-JJTeO0A8YwC)

Use the default command line:
```bash
python eval.py
```

The output somehow looks like:
![x8](https://s2.ax1x.com/2019/01/14/FxI36J.png)
_backup [link](https://imgchr.com/i/FxI36J)_

I use `DBPN_x4.pth` and 
```bash
python eval.py --scale_factor=4 --model=models/DBPN_x4.pth --test_dataset=Set5_LR_x4
```

The output looks like:
![x4](https://s2.ax1x.com/2019/01/14/FxIY01.png)
_backup [link](https://imgchr.com/i/FxIY01)_

Any ideas? @alterzero

**Comment by alterzero** [comment]
Hi,

Set --residual to False and use --model_type DBPNLL for DBPNLL_x8
For DBPN_x8, use --model_type DBPN and --residual to False

**Comment by LoSealL** [comment]
Thanks, solved.
_P.S. The default value of --model is miss spelled corresponding to the downloaded file name (x8 -> 8x)_

**Comment by alterzero** [comment]
Thanks
