### ISSUE TITLE
Evaluate test data 

### ISSUE THREAD

**Issue by RaminAbbaszadi** [alterzero/DBPN-Pytorch#31]
Thanks for your source code. When I try eval code with 2x, 4x, and 8x rescale parameters. I found that 2x, 4x results have some problems in color. I attached SR result. I am appreciate you if you reply me.

For 2x:
![woman_x2](https://user-images.githubusercontent.com/15646332/51299668-4637d400-1a3a-11e9-8318-1c105b21ab5e.png)

For 4x:
![woman_x4](https://user-images.githubusercontent.com/15646332/51299734-813a0780-1a3a-11e9-8fbb-8fd1f1ee45e1.png)

For 8x:
 
![woman_x8](https://user-images.githubusercontent.com/15646332/51299773-9a42b880-1a3a-11e9-838a-703103069365.png)

**Comment by alterzero** [comment]
Carefully check the parameter for --model. There are two model: DBPN and DBPNLL.
Also set --residual to False.

I have just updated the code, removing if clause on the weights loading.
So, if the --model and --weight has different structure, it will cause error.

**Comment by RaminAbbaszadi** [comment]
Thank you. problem solved. 
Best Regards

**Comment by Lelouch422** [comment]
Hi@alterzero, could you please tell the difference between the two models DBPN and DBPNLL, thanks a lot!

**Comment by alterzero** [comment]
Hi @Lelouch422 DBPNLL is the deeper model. While DBPN uses T=7 (T is number of bp stage), DBPNLL uses T=10
