### ISSUE TITLE
Code for Recurrent Back-Projection Network for Video Super-Resolution

### ISSUE THREAD

**Issue by ankit-ai** [alterzero/DBPN-Pytorch#33]
Wanted to know if you can make the code for Recurrent Back-Projection Network for Video Super-Resolution available, I would like to compare it with our method and offer a citation.

Thanks,
Ankit

**Comment by alterzero** [comment]
The code is available https://github.com/alterzero/RBPN-PyTorch
Thanks for your interest in our work

**Comment by ankit-ai** [comment]
Thanks for your prompt response, are there external scripts used to calculate average PSNR and SSMI to reproduce the numbers in the paper?

**Comment by alterzero** [comment]
Yes, I use MATLAB to calculate both PSNR and SSIM.
I will upload the script soon
