### ISSUE TITLE
GAN Training

### ISSUE THREAD

**Issue by ankit-ai** [alterzero/DBPN-Pytorch#34]
Hello,

Are there any published details on the GAN setting of the model? Specific hyperparameters and comparison with non-GAN setting?

Thanks,
Ankit

**Comment by alterzero** [comment]
Now, I'm preparing the journal extension. 
The manuscript will include explanation of the GAN setting and some improvement to the model. 
I will upload it to arXiv then post the link here and of course with the pretrained model.
