### ISSUE TITLE
Which one is better method for upblock/downblock?

### ISSUE THREAD

**Issue by junhyukk** [alterzero/DBPN-Pytorch#6]
Hello,
Thank you for your work!
I am wondering that which one is better for upblock or downblock??

- UpBlock  vs UpBlockPix?
- DownBlock vs DownBlockPix?

UpBlock and DownBlock are used in your code (base_networks.py), 
Are they chosen because they are better than another?

**Comment by alterzero** [comment]
Hi,

I did not find any significant improvement. However, I can say that I'm not doing a comprehensive investigation on that.
