### ISSUE TITLE
ImportError:cannot import name 'Resize'

### ISSUE THREAD

**Issue by ishudi** [alterzero/DBPN-Pytorch#7]
Thank you for such excellent work,but I got a stuck following.

File "../DBPN-Pytorch-master/data.py", line 5, in <module>
   from torchvision.transforms import Compose, CenterCrop, ToTensor, Resize
ImportError: cannot import name 'Resize'

My torch version is 0.4.0, and I found out 'torchvision.transforms' in this version including the function 'Resize' in the website https://pytorch.org/docs/stable/torchvision/transforms.html 
So I want to know why can't I import the 'Resize'，hope for reply,thanks.

**Comment by kuroyanagi33** [comment]
@ishudi With pytorch 0.3.1, torchvision 0.2.0, it can run without problem.

**Comment by ishudi** [comment]
@kuroyanagi33 Thank you very much!  It finally works.

**Comment by arpita739** [comment]
what can be alternatively done?
