### ISSUE TITLE
running bug_ from: too many arguments

### ISSUE THREAD

**Issue by ynieWXJB** [alterzero/DBPN-Pytorch#9]
Hi,

Thanks for your fantastic work!

When I was running the codes, it continues appearing the sentence which is 'from: too many arguments'. I have googled this but unfortunately I didn't find useful solutions to this problem.

Anyone also come with this problem? 
Does anyone has some ideas to deal with this problem?

Many thanks

Alex

**Comment by alterzero** [comment]
Hi,

Can you show me how you run the code?

**Comment by ynieWXJB** [comment]
Hi,

Thanks for your message.

At the very beginning, I mistook keeping running the code by typing 'sh eval.py'. So it continues to show this error. Now, I realized that it is different from EDSR and can run the code without problem. 

However, I got another problems. I don't know if others also got the same one. I can only run the model 'NTIRE2018_x8'. For other models, it continues to give me errors which are dimensions in the checkpoint are not right. I am not sure if the author changed some parameters in the code which are not corresponding with those in other models.


Many thanks

**Comment by alterzero** [comment]
There two types of networks: DBPN and DBPNLL. 
DBPNLL (deeper network) was used for NTIRE2018 competition.
For other model, you just need to add --model_type 'DBPN'

**Comment by ynieWXJB** [comment]
Right, I have been aware of this in the code. 

There is something wrong with the server in our lab. I will try this later.

By the way, I am always confused about one point in the paper. The author of EDSR didn't say PSNR at 8-scale. So you train the 8-scale EDSR model and calculate PSNR by yourself? If it is, how do you guarantee the performance? I mean the authors of EDSR have trained theirs model for eight days. 

Thanks a lot

**Comment by alterzero** [comment]
Yes, we have to train EDSR for x8 by ourself because the author does not provide it. 
We tried to use their recommendation for training, so it should be fair enough. I think it took me around 8 days also to finish the training.
